#!/bin/bash

set -e

case "$1" in
	configure)
		echo "Nothing special to do for Blue Blast Orange"
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		echo "$1"
		;;
	*)
		echo "postinst called with unknown argument \`\$1'" >&2
		exit 0
  		;;
esac
