#!/bin/bash

set -e

case "$1" in
	remove)
		echo "Nothing special to do for Blue Blast Orange!"
		;;
	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		echo "$1"
		;;
	*)
		echo "postrm called with unknown argument \`\$1'" >&2
		exit 0
  		;;
esac
